---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: magento
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: mariadb:10.4
          name: mariadb
          env:
        - name: MARIADB_USER
          value: "exmaple-user"
        - name: MARIADB_PASSWORD
          value: "my_cool_secret"
        - name: MARIADB_ROOT_PASSWORD
          value: "my_super_secret"
        - name: MARIADB_DATABASE
          value: "magento"
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            requests:
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb
  namespace: magento
spec:
  ports:
    - name: "3306"
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mariadb
  type: ClusterIP
